### ISSUE TITLE
Error during loading of extension

### ISSUE THREAD

**Issue by aplavin** [JuliaStats/LogExpFunctions.jl#67] opened 2023-02-22 22:45 UTC
Loading LogExpFunctions and one of its weakdeps in a clean env on 1.9-beta4:
```julia
julia> using LogExpFunctions, InverseFunctions
 │ Packages [LogExpFunctions, InverseFunctions] not found, but
 │ packages named [LogExpFunctions, InverseFunctions] are
 │ available from a registry. 
 │ Install packages?
 │   (@v1.9) pkg> add LogExpFunctions InverseFunctions 
 └ Select environment:
 > 1: `/tmp/jl_PYeWrG` (/tmp/jl_PYeWrG)
   2: `~/.julia/environments/v1.9/Project.toml` (@v#.#)
   Resolving package versions...
    Updating `/tmp/jl_PYeWrG/Project.toml`
  [3587e190] + InverseFunctions v0.1.8
  [2ab3a3ac] + LogExpFunctions v0.3.22
    Updating `/tmp/jl_PYeWrG/Manifest.toml`
  [ffbed154] + DocStringExtensions v0.9.3
  [3587e190] + InverseFunctions v0.1.8
  [92d709cd] + IrrationalConstants v0.1.1
  [2ab3a3ac] + LogExpFunctions v0.3.22
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [ca575930] + NetworkOptions v1.2.0
  [de0858da] + Printf
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [8dfed614] + Test
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll v1.0.2+0
  [4536629a] + OpenBLAS_jll v0.3.21+0
  [8e850b90] + libblastrampoline_jll v5.4.0+0
┌ Error: Error during loading of extension InverseFunctionsExt of LogExpFunctions, use `Base.retry_load_extensions()` to retry.
└ @ Base loading.jl:1191
```

**Comment by devmotion** [comment] 2023-02-22 22:50
I'll close this issue since it seems to be a duplicate of #66 and https://github.com/JuliaLang/julia/issues/48737 which might be fixed on Julia master by https://github.com/JuliaLang/julia/pull/48703. I guess it's good that these issues show up and are fixed in the beta releases but you should switch to a stable release if you want to avoid such problems.

**Closed by devmotion** 2023-02-22 22:50 UTC
