### ISSUE TITLE
Some tests failing on macOS

### ISSUE THREAD

**Issue by cossio** [JuliaStats/LogExpFunctions.jl#78] opened 2023-11-11 16:06 UTC
Running the test suite on macOS I get:

```
log2mexp: Test Failed at ~/Julia/Forks/LogExpFunctions.jl/test/basicfuns.jl:173
  Expression: log2mexp(-(T(1))) ≈ log(2 - exp(-(T(1))))
   Evaluated: 0.23447205f0 ≈ 0.48988014f0
```

Tests pass on Ubuntu (which the only platform currently covered by CI).

**Comment by devmotion** [comment] 2023-11-11 18:43
Possibly caused by the bug fixed in https://github.com/JuliaLang/julia/pull/50989 (see the discussion in #74)? Can you try with Julia 1.10 or master?

**Comment by devmotion** [comment] 2023-11-11 19:45
You can check whether you're Julia version is affected by the bug e.g. by
```julia
for T in (Float32, Float16)
    @test expm1(T(-1.1)) ≈ expm1(big(T(-1.1)))
end
```
(the test added in the Julia bugfix) or checking the output of
```julia
julia> Float16(expm1(-exp(big(Float16(0.1)))))
Float16(-0.669)

julia> expm1(-exp(Float16(0.1)))
Float16(-0.338)

julia> Float32(expm1(-exp(big(Float32(0.1)))))
-0.6688457f0

julia> expm1(-exp(Float32(0.1)))
-0.3376915f0
```

**Comment by devmotion** [comment] 2023-11-11 19:52
It will also be part of Julia 1.9.4: https://github.com/JuliaLang/julia/compare/v1.9.3...release-1.9

**Closed by devmotion** 2023-11-11 19:52 UTC
